library(flexdashboard)
library(knitr)
library(crosstalk)
library(DT)
library(ggplot2) 
library(plotly)
library(stringr)
library(reshape2)
library(readxl)
library(dplyr)
library(tidyr)
library(reactable)
library(formattable) 
library(base64enc)
library(png)
library(patchwork)
library(devtools) 
library(htmltools)
library(lubridate)
library(kableExtra)
library(data.table)
library(quarto)
library(foreign)

currentyear <- 2023