---
title: "domestic-abuse-1"

---



```{r}
#| include: FALSE

library(here)
source(here("data_prep/domabuse_data_prep.R"))
```

## Row

### Column {width=50%}


```{r}
#| title: Number of police recorded domestic abuse incidents and crimes
#| fig-height: 10

DA_chart1 <- plot_ly(
  DA_chart1_data,
  x = ~Year,
  y = ~Incidents,
  type = 'scatter',
  mode = 'lines+markers',
  name = "Incidents",
  line = list(color = nisra_colours[[1]]),
  marker = list(color = nisra_colours[[1]]),
  hoverinfo = 'text',
  text = ~paste0(Year, "<br>Incidents: ", format(Incidents, big.mark = ","))
) %>%
  add_trace(
    y = ~Crimes,
    mode = 'lines+markers',
    name = "Crimes",
    line = list(color = nisra_colours[[2]]),
    marker = list(color = nisra_colours[[2]]),
    text = ~paste0(Year, "<br>Crimes: ", format(Crimes, big.mark = ",")),
    hoverinfo = 'text'
  ) %>%
  layout(
    showlegend = TRUE,
    legend = list(x = 1, xref = "paper", xanchor = "right",
                  y = 1, yref = "paper", yanchor = "bottom"),
    font = list(family = "Arial", size = 14),
    margin = list(t = 40),
    xaxis = list(
      title = list(text = "Year", standoff = 10),
      type = "category",  
      categoryorder = "array",
      categoryarray = DA_chart1_data$Year,  
      tickmode = "array",
      tickvals = DA_chart1_data$Year[seq(1, length(DA_chart1_data$Year), by = 5)],
      ticktext = DA_chart1_data$Year[seq(1, length(DA_chart1_data$Year), by = 5)],
      showline = TRUE,
      linecolor = "#000000",
      showgrid = FALSE,
      ticks = "",
      tickwidth = 2,
      tickangle = 0,
      automargin = TRUE
    ),
    yaxis = list(
      title = "",
      showline = TRUE,
      linecolor = "#000000",
      showgrid = FALSE,
      rangemode = "tozero",
      tickformat = ",.0f"
    ),
    annotations = list(
      list(
        x = 0, y = 1.025,
        text = "Incidents and Crimes",
        showarrow = FALSE,
        xref = "paper", yref = "paper",
        xanchor = "center", yanchor = "bottom",
        font = list(size = 14, color = "black")
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

div(
  DA_chart1,
  p("Police recorded crime data is a victim oriented approach to crime recording. A crime will be recorded as having a domestic abuse motivation where it meets the relevant definition provided above. Not all domestic abuse incidents will result in the recording of a crime, as what has occurred in the incident may not be of the level of severity that would result in a crime being recorded. (From PSNI DA report)"),
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.psni.police.uk%2Fsystem%2Ffiles%2F2025-05%2F386082373%2FDomestic%2520Abuse%2520Tables%2520Period%2520Ending%252031st%2520March%25202025.xlsx&wdOrigin=BROWSELINK",
      "Trends in domestic abuse incidents and crimes recorded by the police since 2004/05 (Figure 1) (opens in a new tab)",
      target = "_blank"
    )
  )
)



```

### Column {width=50%}

### Dpmestic Abuse {.tabset}

#### Chart 2

```{r}
#| title: Percentage of police recorded domestic abuse crimes in 2024/25, by crime type

DA_chart2 <- plot_ly(
  data = DA_chart2_data,
  labels = ~`Crime Type`,
  values = ~Percentage,
  type = 'pie',
  text = ~paste0(Percentage, "%"),   # show % inside
  textinfo = "text",
  textposition = "inside",
  sort = FALSE,
  direction = "clockwise",
  marker = list(colors = nisra_colours[1:5]),
  hoverinfo = 'text',
  hovertext = ~paste0(
    da_currentyear, "<br>",
    `Crime Type`, ": ", format(Count, big.mark = ","), "<br>",
    "Share: ", Percentage, "%"
  )
) %>%
  layout(
    title = " ",
    font = list(family = "Arial", size = 14),
    showlegend = TRUE,   # ✅ turn legend back on
    legend = list(
      orientation = "v", # vertical legend on the right
      x = 1,
      xanchor = "left",
      y = 0.5,
      yanchor = "middle"
    )
  ) %>%
  config(displayModeBar = FALSE)

div(
  DA_chart2,
  p("Note 1: Including homicide and death or serious injury-unlawful driving."),
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.psni.police.uk%2Fsystem%2Ffiles%2F2025-05%2F386082373%2FDomestic%2520Abuse%2520Tables%2520Period%2520Ending%252031st%2520March%25202025.xlsx&wdOrigin=BROWSELINK",
      "Domestic Abuse Incidents and Crimes Recorded by the Police in Northern Ireland: Update to 31 March 2025 (Table 1 and Figures 5 & 6) (opens in a new tab)",
      target = "_blank"
    )
  )
)
```

#### Chart 3

```{r}
#| title: Prevalence of domestic abuse among adults, by gender

DA_chart3 <- plot_ly(
  data = DA_chart3_data,
  x = ~Group,
  y = ~Percentage,
  color = ~category,
  colors = nisra_colours[1:2],
  type = "bar",
  barmode = "group",
  text = ~paste0(category, "<br>", Group, ": ", round(Percentage), "%"),
  hoverinfo = "text"   
) %>%
  layout(
    title = "",
    margin = list(t = 40),
    xaxis = list(title = "Group"),
    yaxis = list(
      title = "",        
      showline = TRUE,   
      zeroline = TRUE,   
      showticklabels = TRUE  
    ),
    legend = list(title = list(text = "Category"),
                  x = 1, xref = "paper", xanchor = "right",
                  y = 1, yref = "paper", yanchor = "bottom"),
    annotations = list(
      list(
        x = -0.008,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

div(
  DA_chart3,
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.justice-ni.gov.uk%2Fsites%2Fdefault%2Ffiles%2Fpublications%2Fjustice%2Fexperience%2520of%2520domestic%2520abuse%2520findings%2520from%2520the%2520201819%2520niscs.xl_.XLSX&wdOrigin=BROWSELINK",
      "Findings from the 2018/19 Northern Ireland Safe Community Survey (Table 1 and Table 5) (opens in a new tab)",
      target = "_blank"
    )
  )
)



```

