---
title: "domestic-abuse-2"
---



```{r}
#| include: FALSE

library(here)
source(paste0(here(), "/data_prep/domabuse_data_prep.R"))
```

## Row

### Column {width=50%}

```{r}
#| title: Percentage of Domestic Abuse Experience by Gender 2018/19
#| fig-height: 10

DA_chart3 <- plot_ly(
  data = DA_chart3_data,
  x = ~Gender,
  y = ~Percentage,
  type = 'bar',
  marker = list(color = nisra_colours[2]),
  text = ~paste0(
    da_chart3_currentyear, "<br>",
    Gender, ": ", Percentage, "%"
  ),
  hoverinfo = "text",       
  textposition = "none"     
) %>%
  layout(
    title = " ",
    margin = list(t = 50),  
    xaxis = list(
      title = "Gender",
      showline = TRUE,      
      linecolor = "black"   
    ),
    yaxis = list(
      title = "",           
      showline = TRUE,      
      linecolor = "black",  
      zeroline = FALSE      
    ),
    annotations = list(
      list(
        x = -0.07,          
        y = 1.05,           
        text = "Percentage %",
        xref = "paper",
        yref = "paper",
        showarrow = FALSE,
        xanchor = "left",
        yanchor = "bottom",
        font = list(size = 14)
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

DA_chart3




```


### Column {width=50%}

```{r}
#| title: Title
#| fig-height: 10

#Create hover text dynamically
DA_chart4_data$hover_text <- paste0(
  DA_chart4_data$Gender, "<br>",
  DA_chart4_data$Categories, ": ", 
  DA_chart4_data$Percentage, "%"
)

# Calculate dynamic y-axis range with 5% padding above max value
y_max <- max(DA_chart4_data$Percentage, na.rm = TRUE) * 1.05

DA_chart4 <- plot_ly(
  data = DA_chart4_data,
  x = ~Categories,
  y = ~Percentage,
  color = ~Gender,
  colors = c(nisra_colours[1], nisra_colours[2], nisra_colours[5]),
  type = 'bar',
  text = ~hover_text,        
  textposition = 'auto',     
  hoverinfo = 'text'
) %>%
  layout(
    barmode = 'group',        
    yaxis = list(
      title = '',
      tickformat = '.0f',
      range = c(0, y_max),     
      showline = TRUE,        
      linecolor = 'black',    
      linewidth = 1           
    ),
    xaxis = list(
      title = '',
      tickangle = 0,
      showline = TRUE,
      linecolor = 'black',
      linewidth = 1
    ),
    legend = list(title = list(text = 'Gender')),
    margin = list(t = 50),
    annotations = list(
      list(
        x = -0.008,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

DA_chart4


```
