---
title: "NILT"
---



```{r}
#| include: FALSE

library(here)
source(here("data_prep/main_data_prep.R"))
```

## Row

### Column {width=50%}

```{r}
#| title: Experience of gender-based violence in the last five years  (% of all respondents)
#| fig-height: 10

plot_ly() %>%
  add_trace(data = nilt_historical_chart1, x = ~year, y = ~GBVPHYVA, type = 'scatter',
            mode = 'lines+markers', name = 'Physical violence',
            line = list(color = nisra_colours[1]),
            marker = list(color = nisra_colours[1]),
            hovertemplate = "%{x}<br>%{fullData.name}: %{y:.2f}%<extra></extra>") %>%
  add_trace(data = nilt_historical_chart1, x = ~year, y = ~GBVSEXVA, type = 'scatter',
            mode = 'lines+markers', name = 'Sexual violence',
            line = list(color = nisra_colours[2]),
            marker = list(color = nisra_colours[2]),
            hovertemplate = "%{x}<br>%{fullData.name}: %{y:.2f}%<extra></extra>") %>%
  add_trace(data = nilt_historical_chart1, x = ~year, y = ~GBVPSYVA, type = 'scatter',
            mode = 'lines+markers', name = 'Psychological violence',
            line = list(color = nisra_colours[3]),
            marker = list(color = nisra_colours[3]),
            hovertemplate = "%{x}<br>%{fullData.name}: %{y:.2f}%<extra></extra>") %>%
  add_trace(data = nilt_historical_chart1, x = ~year, y = ~GBVECONV, type = 'scatter',
            mode = 'lines+markers', name = 'Economic violence',
            line = list(color = nisra_colours[4]),
            marker = list(color = nisra_colours[4]),
            hovertemplate = "%{x}<br>%{fullData.name}: %{y:.2f}%<extra></extra>") %>%
  add_trace(data = nilt_historical_chart1, x = ~year, y = ~GBVONLV, type = 'scatter',
            mode = 'lines+markers', name = 'Online violence',
            line = list(color = nisra_colours[5]),
            marker = list(color = nisra_colours[5]),
            hovertemplate = "%{x}<br>%{fullData.name}: %{y:.2f}%<extra></extra>") %>%
  layout(
    margin = list(t = 40),
    xaxis = list(
      title = list(
        text = "Year",
        font = list(size = 14)
      ),
      tickmode = "array",
      tickvals = nilt_historical_chart1$year,
      showgrid = FALSE,
      showline = TRUE,  
      linecolor = "black", 
      linewidth = 1 
    ),
    yaxis = list(
      title = "",  
      automargin = TRUE,
      titlefont = list(size = 0),
      standoff = 0,
      showgrid = FALSE,
      showline = TRUE, 
      linecolor = "black",
      linewidth = 1,
      rangemode = "tozero"
    ),
    legend = list(title = list(text = "")),
    annotations = list(
      list(
        x = -0.008,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    hoverlabel = list(
      font = list(color = "white")  # <-- Sets hover text to white
    )
  ) %>%
  config(displayModeBar = FALSE)


```


### Column {width=50%}

```{r}
#| title: Experience of gender-based violence in the last five years (%)

violence_labels <- c(
  GBVPHYVA = "Physical violence",
  GBVSEXVA = "Sexual violence",
  GBVPSYVA = "Psychological violence",
  GBVECONV = "Economic violence",
  GBVONLV  = "Online violence"
)

nilt_historical_charts <- bind_rows(nilt_historical_chart2,
                                    nilt_historical_chart3) %>% 
  mutate(year = as.character(year),
         variable_label = recode(variable, !!!violence_labels),
         gender = factor(gender, levels = c("Female", "Male")),
         age = factor(age, levels = c("Age 18-29", "All respondents")))

shared_nilt <- SharedData$new(
  nilt_historical_charts,
  key = ~variable,
  group = "violence_type"
)

unique_years <- sort(unique(nilt_historical_charts$year))


filter_select(
  id = "var_filter",
  selected = "Sexual violence",
  label = "Select Violence Type",
  sharedData = shared_nilt,
  group = ~variable_label,
  multiple = FALSE
)

h3("By gender")

plot_ly(shared_nilt, 
        x = ~year, 
        y = ~percentage_yes, 
        color = ~gender, 
        colors = c(nisra_colours[1], nisra_colours[2]),
        type = 'scatter', 
        mode = 'lines+markers',
        hoverinfo = "text",
        text = ~paste0(
                year,
                "<br>", gender,
                "<br>", variable_label, ": ", sprintf("%.2f%%", percentage_yes)
)) %>%
  layout(
      xaxis = list(
      title = "Year",
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      tickvals = unique_years,
      ticktext = unique_years
    ),
    
    yaxis = list(
      title = "",  
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      rangemode = "tozero"
    ),
    
    legend = list(title = list(text = "")),
    margin = list(t = 40),  
    annotations = list(
      list(
        x = -0.008,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    
    hoverlabel = list(
      font = list(color = "white")
    )
  ) %>%
  config(displayModeBar = FALSE)


h3("By age")

plot_ly(shared_nilt, 
        x = ~year, 
        y = ~percentage_yes, 
        color = ~age, 
        colors = c(nisra_colours[1], nisra_colours[2]),
        type = 'scatter', 
        mode = 'lines+markers',
        hoverinfo = "text",
        text = ~paste0(year,
                      "<br>", age,
                      "<br>", variable_label, ": ", sprintf("%.2f%%", percentage_yes))) %>%
  layout(
      xaxis = list(
      title = "Year",
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      tickvals = unique_years,
      ticktext = unique_years
    ),
    
    yaxis = list(
      title = "",  # remove y-axis title
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      rangemode = "tozero"
    ),
    
    legend = list(title = list(text = "")),
    margin = list(t = 40),  
    annotations = list(
      list(
        x = -0.008,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    
    hoverlabel = list(
      font = list(color = "white")
    )
  ) %>%
  config(displayModeBar = FALSE)
```

## Row
Source: [Ending Violence Against Women and Girls: Experiences and attitudes of adults in Northern Ireland in 2023](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.executiveoffice-ni.gov.uk%2Fsites%2Fdefault%2Ffiles%2F2024-12%2Fdata-tables.xlsx&wdOrigin=BROWSELINK)