---
title: "recorded-crime"
---



```{r}
#| include: FALSE

library(here)
source(here("data_prep/recordedcrime_data_prep.R"))
```

## Row

### Column {width=50%}

```{r}
#| title: Police recorded crime by offence
#| fig-height: 10


# Prepare ticks for category years like "2024/25"
years <- as.character(police_recorded_crime_historical_chart1$Year)
tick_every_5 <- years[seq(1, length(years), by = 5)]

prc_plot1<- plot_ly(police_recorded_crime_historical_chart1, x = ~Year) %>%
  add_trace(
    y = ~Other,
    name = "Other",
    text = ~paste(
      Year,
      paste0(
        "Other: ",
        format(Other, big.mark = ",")
      ),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[4]),   
    marker = list(color = nisra_colours[4])
  ) %>%
  add_trace(
    y = ~`Violence Against the Person (excluding stalking and harassment)`,
    name = "Violence Against the Person<br>(excluding stalking<br>and harassment)",
    text = ~paste(
      Year,
      paste0(
        "Violence Against the Person<br>(excluding stalking and harassment): ",
        format(`Violence Against the Person (excluding stalking and harassment)`, big.mark = ",")
      ),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[2]),
    marker = list(color = nisra_colours[2])
  ) %>%
  add_trace(
    y = ~`Stalking and Harassment`,
    name = "Stalking and Harassment",
    text = ~paste(
      Year,
      paste0(
        "Stalking and Harassment: ",
        format(`Stalking and Harassment`, big.mark = ",")
      ),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[1]),
    marker = list(color = nisra_colours[1])
  ) %>%
  add_trace(
    y = ~Sexual,
    name = "Sexual",
    text = ~paste(
      Year,
      paste0(
        "Sexual: ",
        format(Sexual, big.mark = ",")
      ),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[3]),
    marker = list(color = nisra_colours[3])
  ) %>%
  layout(
    margin = list(t = 60),
    xaxis = list(
      type = "category",
      categoryorder = "array",
      categoryarray = years,
      tickmode = "array",
      tickvals = tick_every_5,
      ticktext = tick_every_5,
      tickangle = 0,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      showgrid = FALSE,
      zeroline = FALSE
    ),
    yaxis = list(
      title = list(text = ""),
      rangemode = "tozero",
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      zeroline = FALSE,
      tickformat = ",d"
    ),
    annotations = list(
      list(
        x = 0.00, xref = "paper", xanchor = "center",
        y = 1.025, yref = "paper", yanchor = "bottom",
        text = "Number of<br>crimes",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    legend = list(
      x = 1, xref = "paper", xanchor = "right"
    )
  ) %>%
  config(displayModeBar = FALSE)

div(
  prc_plot1,
  p("Violence Against the Person includes Homicide, Death or serious injury - unlawful driving, Violence with injury, Violence without injury. It does not include Stalking and Harassment."),
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.psni.police.uk%2Fsystem%2Ffiles%2F2025-05%2F861739285%2FPolice%2520Recorded%2520Crime%2520Tables%2520Period%2520Ending%252031st%2520March%25202025.xlsx&wdOrigin=BROWSELINK",
      "Police recorded crime by offence, 2001/02 to 2024/25 (Table 15) (opens in a new tab)",
      target = "_blank"
    )
  )
)

```


### Column {width=50%}

```{r}
#| title: Police recorded online crime by offence
#| fig-height: 10

# Prepare ticks for category years like "2024/25"
years <- as.character(police_recorded_crime_historical_chart2$Year)
tick_every_5 <- years[seq(1, length(years), by = 5)]

prc_plot2 <- plot_ly(police_recorded_crime_historical_chart2, x = ~Year) %>%
  add_trace(
    y = ~Other,
    name = "Other",
    text = ~paste(
      Year,
      paste0("Other: ", format(Other, big.mark = ",")),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[4]),
    marker = list(color = nisra_colours[4])
  ) %>%
  add_trace(
    y = ~`Violence Against the Person (excluding stalking and harassment)`,
    name = "Violence Against the Person<br>(excluding stalking<br>and harassment)",
    text = ~paste(
      Year,
      paste0(
        "Violence Against the Person<br>(excluding stalking and harassment): ",
        format(`Violence Against the Person (excluding stalking and harassment)`, big.mark = ",")
      ),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[2]),
    marker = list(color = nisra_colours[2])
  ) %>%
  add_trace(
    y = ~`Stalking and Harassment`,
    name = "Stalking and Harassment",
    text = ~paste(
      Year,
      paste0("Stalking and Harassment: ", format(`Stalking and Harassment`, big.mark = ",")),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[1]),
    marker = list(color = nisra_colours[1])
  ) %>%
  add_trace(
    y = ~Sexual,
    name = "Sexual",
    text = ~paste(
      Year,
      paste0("Sexual: ", format(Sexual, big.mark = ",")),
      sep = "<br>"
    ),
    hoverinfo = "text",
    type = "scatter", mode = "lines+markers",
    line = list(color = nisra_colours[3]),
    marker = list(color = nisra_colours[3])
  ) %>%
  layout(
    margin = list(t = 60, r = 140),  # extra right margin for the legend outside the plot
    xaxis = list(
      type = "category",
      categoryorder = "array",
      categoryarray = years,
      tickmode = "array",
      tickvals = tick_every_5,
      ticktext = tick_every_5,
      tickangle = 0,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      showgrid = FALSE,
      zeroline = FALSE
    ),
    yaxis = list(
      title = list(text = ""),
      rangemode = "tozero",
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      zeroline = FALSE,
      tickformat = ",d"
    ),
    annotations = list(
      list(
        x = 0.00, xref = "paper", xanchor = "center",
        y = 1.025, yref = "paper", yanchor = "bottom",
        text = "Number of<br>online crimes",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    legend = list(
      x = 1.05,          
      xref = "paper",
      xanchor = "left",  
      y = 1,
      yanchor = "top"
    )
  ) %>%
  config(displayModeBar = FALSE)

div(
  prc_plot2,
  p(
    "Source: ",
    a(
      href = "https://www.psni.police.uk/system/files/2025-01/444101239/Police_Recorded_Crime_in_Northern_Ireland_1998-99_to_2023-24_revised.xlsx",
      "Police recorded online crime by offence, 2001/02 to 2024/25 (Table 4.1) (opens in a new tab)",
      target = "_blank"
    )
  )
)

```

