---
title: "recorded-crime"
---



```{r}
#| include: FALSE

library(here)
source(here("data_prep/recordedcrime_data_prep.R"))
```


```{r}

tmap_mode("view")

make_rc_map <- function(df, value_col, title_lab) {
  tm_shape(
    df %>% select(LGDNAME, all_of(value_col)),
    name = title_lab,
    unit = "imperial"
  ) +
    tm_basemap("Esri.WorldGrayCanvas") +
    tm_polygons(
      col = value_col,
      n = 3,
      style = "quantile",
      palette = "Blues",
      alpha = 0.5,
      border.alpha = 1,
      legend.show = TRUE,
      title = title_lab,   
      popup.vars = setNames(
        c("LGDNAME", value_col),
        c("Council area: ", paste0(title_lab, " value: "))
      )
    ) +
    tm_scale_bar(width = 250) +
    tm_view(
      view.legend.position = c("left", "top"),
      control.position = c("left", "bottom"),
      leaflet.options = c(
        zoomControl = TRUE,       
        dragging = TRUE,          
        keyboard = TRUE,
        boxZoom = TRUE,
        doubleClickZoom = TRUE,
        scrollWheelZoom = TRUE,
        tap = TRUE,
        touchZoom = TRUE,
        attributionControl = FALSE
      )
    )
}
```

### Maps {.tabset}

#### Sexual Offences

```{r}
make_rc_map(NI_map_data, "sexual_value", "Sexual Offences")
```

#### Stalking and Harassment

```{r}
make_rc_map(NI_map_data, "stalking_value", "Stalking and Harassment")
```

#### Violence Against the Person <span class="tab-break">(Excluding Stalking and Harassment)</span>

```{r}
make_rc_map(NI_map_data, "violence_value", "Violence Against the Person (Excluding Stalking and Harassment) ")
```

#### Other

```{r}
make_rc_map(NI_map_data, "other_value", "Other")
```