---
title: "recorded-crime"
---



```{r}
#| include: FALSE

library(here)
source(here("data_prep/recordedcrime_data_prep.R"))
```

## Row

### Column {width=100%}

```{r}
#| title: Victims of police recorded crime, by crime type and gender (%)
#| fig-height: 10

shared_victims <- SharedData$new(
  all_police_recorded_crime_victims,
  key = ~Crime_Type
)

filter_select(
  id = "var_filter",
  selected = "Total police recorded crime",
  label = "Select Violence Type",
  sharedData = shared_victims,
  group = ~Crime_Type,
  multiple = FALSE
)

tick_every_5 <- all_police_recorded_crime_victims$Year[seq(1, length(unique(all_police_recorded_crime_victims$Year)), by = 5)]

victims_plot<- plot_ly(shared_victims, 
        x = ~Year, 
        y = ~Value, 
        color = ~Victim_Gender, 
        colors = c(nisra_colours[1], nisra_colours[2], nisra_colours[3]),
        type = 'scatter', 
        mode = 'lines+markers',
        hoverinfo = "text",
        text = ~paste0(
                Year,
                "<br>", Victim_Gender,
                "<br>", Crime_Type, ": ", sprintf("%.0f%%", Value)
)) %>%
  layout(
      xaxis = list(
      title = "Year",
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      tickvals = tick_every_5,
      ticktext = tick_every_5
    ),
    
    yaxis = list(
      title = "",  
      showgrid = FALSE,
      showline = TRUE,
      linecolor = "black",
      linewidth = 1,
      rangemode = "tozero",
      range = c(0, 60)
    ),
    legend = list(title = list(text = ""),
                  x = 1, xref = "paper", xanchor = "right"),
    margin = list(t = 40),  
    annotations = list(
      list(
        x = 0.00,
        xref = "paper",
        xanchor = "center",
        y = 1.025,
        yref = "paper",
        yanchor = "bottom",
        text = "Percentage %",
        showarrow = FALSE,
        font = list(size = 14)
      )
    ),
    
    hoverlabel = list(
      font = list(color = "white")
    )
  ) %>%
  config(displayModeBar = FALSE)



div(
  victims_plot,
  p(
    style = "margin-top: 30px;",
    "Please note that crimes in which the gender of the victim was unknown have not been displayed in this chart; therefore, totals may not sum to 100%."
  ),
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.psni.police.uk%2Fsystem%2Ffiles%2F2025-01%2F444101239%2FPolice_Recorded_Crime_in_Northern_Ireland_1998-99_to_2023-24_revised.xlsx&wdOrigin=BROWSELINK",
      "Police recorded crime from 2007/08 - 2023/24 (Pivot Table-Victim Gender_Age) (opens in a new tab)",
      target = "_blank"
    )
  ),
  p(
    "Source: ",
    a(
      href = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.psni.police.uk%2Fsystem%2Ffiles%2F2025-05%2F861739285%2FPolice%2520Recorded%2520Crime%2520Tables%2520Period%2520Ending%252031st%2520March%25202025.xlsx&wdOrigin=BROWSELINK",
      "Police recorded crime 2024/25 (Pivot Table-Victim Gender_Age) (opens in a new tab)",
      target = "_blank"
    )
  )
)



```


